import React, { useState } from 'react'
import { TextInput, TouchableOpacity, View,Text, Image, ImageBackground,ScrollView } from 'react-native';
import { AntDesign } from '@expo/vector-icons';
import RNPickerSelect from "react-native-picker-select";

function Terms() {
    return (
        <ScrollView>
                <View style={{ 
                    backgroundColor:'white',
                    flex:1
                }}>
                    <Text style={{ 
                        textAlign:'center',
                        marginBottom:'2%',
                        fontWeight:'700',
                        fontSize:18
                    }}>Sittercity Terms of Use and End User License Agreement</Text>
                    <Text style={{ color:'#84847E',marginLeft:'2%',fontSize:10 }}>Last Revised: April 25, 2020</Text>
                    <Text style={{ 
                            fontSize:12,
                            marginLeft:'2%',
                            marginRight:'2%'
                    }}>BY DOWNLOADING THE SITTERCITY OR CHIME APP (COLLECTIVELY, THE “APPS”) OR BY ACCESSING, VIEWING, OR USING THE APPS, THE SITTERCITY OR CHIME WEBSITE (THE “SITES”) OR ANY TOOLS AND SERVICES PROVIDED IN CONNECTION WITH THE APPS OR THE SITES (COLLECTIVELY, THE APPS, THE SITES AND ALL RELATED TOOLS AND SERVICES ARE REFERRED TO AS THE “SERVICE”), YOU UNDERSTAND AND AGREE TO BE BOUND BY ALL TERMS AND CONDITIONS CONTAINED IN THESE TERMS OF USE. IF YOU OBJECT TO ANYTHING IN THESE TERMS OF USE, INCLUDING THE MANDATORY ARBITRATION PROVISION IN SECTION 35 AND CLASS ACTION WAIVER IN SECTION 35, OR OTHERWISE DO NOT UNDERSTAND OR AGREE TO BE BOUND BY THESE TERMS OF USE DO NOT USE THE SERVICE AND UNINSTALL THE APPS IMMEDIATELY.

                            These terms and conditions and end user license agreement (collectively, “Terms of Use”) set forth the terms and conditions of Choice Sitter Solutions, LLC ("Sittercity") applicable to your use of the Service. Sittercity encourages you to read these Terms of Use carefully. For purposes of these Terms of Use, "Sittercity" means and includes Sittercity and its subsidiaries and its and their investors, officers, directors, employees, agents, representatives and assigns. "User" means each person who accesses or uses the Service, including parents and caregivers, whether or not such User personally installed one or both of the Apps or created an account.

                            You understand and agree that Sittercity may revise, modify and/or supplement these Terms of Use (the “Revised Terms of Use”) at any time. Any Revised Terms of Use will be effective immediately after notice is sent to you via the Sittercity internal email system or by such other forms of notice as may be determined by Sittercity. If you do not agree to the Revised Terms of Use, you must stop using the Service and close your account (and uninstall the Apps). You can close your account through the Account Settings page under My Sittercity. By continuing to use the Service following notice, or by failing to close your account or uninstall the Apps, you hereby expressly agree to be bound by the Revised Terms of Use and acknowledge that your continued use of and access to the Service is valid consideration for the Revised Terms of Use.

                            If you are a paying member and you close your account due to rejection of the Revised Terms of Use before your paid membership term has ended, you may seek reimbursement for the paid pro rata balance of the remaining membership by calling Sittercity at 888.748.2489, or by emailing support@sittercity.com.</Text>
                    <Text style={{ 
                        marginLeft:'2%',
                        fontWeight:'700',
                        marginTop:'2%',
                        color:'#84847E',
                        marginBottom:'2%'

                    }}>Terms and Conditions</Text>
                    <Text style={{ 
                        marginLeft:'2%',
                        marginRight:'2%'
                    }}>1. Privacy Policy. Please refer to the Sittercity Privacy Policy at https://www.sittercity.com/privacy for information on how Sittercity collects, uses and discloses information about you.

                            2. License. Subject to the terms and conditions set forth in these Terms of Use, Sittercity grants you a personal, nonexclusive, nontransferable license to use the Service and to download and use the Apps on any mobile device that you own or control, solely for your personal, noncommercial use except as expressly set forth herein.

                            The Service will be in the form and format as determined by Sittercity in its sole discretion from time to time, and such form and format may limit or restrict use to certain types of devices at the exclusion of others, and may have additional licensing terms restricting their use thereto.

                            Such license is subject to these Terms of Use and except as expressly provided in these Terms of Use, does not include: (A) any resale or commercial use (except as expressly set forth herein) of the Service or of any content or materials contained therein ("Sittercity Content"); (B) modifying or otherwise making any derivative uses of the Service or any Sittercity Content; (C) use of any data mining, robots or similar data gathering or extraction methods; (D) reproducing, distributing, publicly performing or publicly displaying the Service or the Sittercity Content; (E) reverse engineering or otherwise attempting to discover any source code; or (F) any use of the Service other than for its intended purpose. Any use of the Service or the Sittercity Content other than as specifically authorized herein, without the prior, written permission of Sittercity, is strictly prohibited and will terminate the license granted herein. Such unauthorized use may also violate applicable laws, including without limitation copyright and trademark laws and applicable communications regulations and statutes. Unless explicitly stated herein, nothing in these Terms of Use shall be construed as conferring any license to intellectual property rights, whether by estoppel, implication or otherwise. This license is revocable at any time.

                            3. Location Information; Consent to Use of Data and Mobile Communications. The Apps may implement a location feature whereby they will automatically collect your geolocation information if you provide your consent. In such event, the Apps will use and share such location to enable Users to determine which Users nearby. Sittercity may also use location information to provide information and advertising to Users. IF YOU WANT TO STOP THE AUTOMATIC COLLECTION OF YOUR LOCATION INFORMATION, YOU MAY DO SO BY USING THE PRIVACY SETTINGS IN THE APPS AND/OR ON YOUR DEVICE AND/OR BY UNINSTALLING THE APPS.

                            You also consent to Sittercity communicating with you about the Service or in connection with the features, functions and activities contained therein by SMS, text message, email or other electronic means. Your carrier's normal, messaging, data and other rates and fees will apply to these communications.

                            4. The Service Offers a Venue. The Service merely offers tools, resources and a venue to connect those seeking care services with those seeking to provide care services. You understand and agree that Sittercity: (A) does not employ, recommend or endorse any Users and has no control over the acts or omissions of any Users; (B) is not responsible or liable in any manner for the performance or conduct of any Users or other third parties online or offline; (C) makes no representations or warranties about the quality of the services provided by any User or about your interactions or dealings with other Users; and (D) does not screen Users or automatically conduct any kind of identity or background checks except as otherwise expressly stated in these Terms of Use or on the Service. Regardless of whether Sittercity screens users or performs a background check, you should exercise caution and perform your own screening before connecting with anyone through the Service, meeting anyone, engaging Users or accepting engagements. Sittercity hereby expressly disclaims, and you hereby expressly release Sittercity from, any and all liability whatsoever for any controversies, claims, suits, injuries, loss, harm and/or damages arising from and/or in any way related to the Service or your interactions or dealings with other Users, including without limitation any acts and/or omissions of Users online or offline. By using the Service, you acknowledge and agree that you are solely responsible for your use of the Service and the connections you make and that ALL USE OF THE SERVICE IS AT YOUR SOLE AND EXCLUSIVE RISK.

                            5. Transactions Are Between Users; Release. The Service may be used to help obtain or offer services provided by Users and to facilitate payment for such services. However, Users transact solely between themselves, and Sittercity is not a party to any transactions between Users. Sittercity hereby expressly disclaims, and you hereby expressly release Sittercity and its affiliates from, any and all liability whatsoever for any controversies, claims, suits, injuries, loss, harm and/or damages arising from and/or in any way related to disputes, dealings, or interactions between you and any other Users or third parties.

                            6. Eligibility. You represent and warrant that you currently meet and will continue to meet the following eligibility conditions ("Eligibility Conditions") for as long as you use the Service: (A) you are at least eighteen (18) years old; (B) you comply with all laws, rules and regulations in connection with your use of the Service and any services arranged through the Service, including without limitation legal authorization to work in the jurisdiction in which you seek to provide or receive services; (C) you have the right, authority and capacity to enter into these Terms of Use and to abide by all of the terms and conditions in these Terms of Use; (D) neither you, nor anyone in your home or, as applicable, the location where care services are provided or received: (i) has been the subject of a complaint, restraining order or any other legal action involving violence, abuse, neglect, fraud, larceny, or any offense that involves endangering the safety of others; (ii) has been convicted of a crime of any nature, including any felony or misdemeanor of any kind, including without limitation any sexual, child abuse or domestic violence offenses; and/or (iii) has been and/or is currently required to register as a sex offender in any jurisdiction or with any government entity; and (E) neither you, nor anyone in your home or, as applicable, the location where care services are provided or received, is currently out on bail or on such person’s own recognizance pending trial, relating to any felony or misdemeanor charges of any kind, including without limitation sexual, child abuse or domestic violence offenses.

                            By using the Service, you understand and agree that Sittercity may rely on the above Eligibility Conditions representations and warranties as true. You understand and agree that Sittercity may revise the Eligibility Conditions from time to time and require new conditions and certifications and that you will abide by such revised Eligibility Conditions or discontinue using the Service and uninstall the Apps and you must discontinue use of the Service if at any time you no longer meet the Eligibility Conditions. If Sittercity becomes aware of or believes that there are violations of the Eligibility Conditions by any User or that the User has otherwise provided any false or misleading information, it may, among other things, suspend and/or terminate such User with or without notice at its sole discretion. If your account is terminated or suspended, you agree to make no further use of the Service after termination or during suspension.

                            You understand and agree that Sittercity does not routinely verify that any or all of the Eligibility Conditions are met by any other Users and you further understand and agree that Sittercity is not responsible for assuring that the Eligibility Conditions are met or for any failure to suspend, terminate or prevent the use of the Service by Users who do not meet the Eligibility Conditions. Except where expressly stated otherwise in these Terms of Use or on the Service, you understand and agree that you are solely responsible for conducting any appropriate background checks and obtaining references prior to engaging another User to perform services. You further understand and agree that you are solely responsible for making your own evaluations, decisions and assessments about whether to engage other Users to perform services, accepting any engagements offered by other Users or otherwise interacting with other Users. Sittercity hereby expressly disclaims, and you hereby expressly release Sittercity and its affiliates from, any and all liability whatsoever for any controversies, claims, suits, injuries, loss, harm or damages arising from or in any way related to: (x) any inaccuracy, untimeliness or incompleteness of a User’s Eligibility Conditions; and/or (y) any misstatements or misrepresentations made by any Users.

                            Although Sittercity has no obligation to verify the Eligibility Conditions or conduct any other screenings, verifications or background checks, it reserves the right to do so in its sole discretion, and you hereby authorize Sittercity to verify any or all of the above representations and warranties you make or the other information you provide. Such verification may include, without limitation, conducting criminal background checks, sex offender registry checks, motor vehicle records checks, identification verifications, credit checks and/or using available public records. You consent to any collection, use or disclosure in order to accomplish such verification. You agree that Sittercity may take such action as it deems appropriate in its sole discretion, including without limitation suspending and/or terminating your account, should it determine, in its sole discretion, that you have violated any representation or warranty or any other provision of these Terms of Use or it otherwise determines in its sole discretion that such suspension or termination is appropriate for any reason. In the event of any suspension or termination, you agree to make no further use of the Service after termination or during suspension.

                            7. No Professional Advice; Information Only. Any information, materials, content and/or advice provided through the Service, whether by Sittercity, Users or third parties, including without limitation the Sittercity blogs, including without limitation at https://www.sittercity.com/parents, https://www.sittercity.com/sitters, the Sittercity Facebook pages, including without limitation at www.facebook.com/sittercity and www.facebook.com/sittercity.dod, the Sittercity Twitter account, including without limitation at www.twitter.com/sittercity, the Sittercity Instagram account, including without limitation at www.instagram.com/sittercity, the Sittercity Pinterest account, including without limitation at www.pinterest.com/sittercity and the Sittercity LinkedIn account, including without limitation at https://www.linkedin.com/company/sittercity, are for informational purposes only. Before starting a project or activity listed in the Compendium, please see the Activity Safety Guide for information about the safe performance of the projects and activities in the Compendium. If you have specific concerns or a situation arises requiring professional advice, you should consult with an appropriately trained and qualified professional. Sittercity hereby expressly disclaims, and you hereby expressly release Sittercity and its affiliates from, any and all liability whatsoever for any controversies, claims, suits, injuries, losses, harms and/or damages arising from and/or in any way related to the information, materials and content provided through the Service, including without limitation on the Compendium, Blog, Facebook pages, Twitter account, Instagram account, Pinterest account, and LinkedIn account.

                            8. Use of the Service. You agree to use the Service in a manner that is lawful, relevant and proper to the applicable forum. Any use of the Service that Sittercity, in its sole discretion, finds inappropriate or offensive or contrary to these Terms of Use may result in suspension or termination of your account with or without notice. Sittercity reserves the right to suspend or terminate your account with or without notice at any time in its sole discretion, for any reason or no reason. In the event of any suspension or termination, you agree to make no further use of the Service after termination or during suspension.

                            You understand and agree not to, and not to permit or encourage anyone else to, do any of the following in connection with the Service:

                            Defame, abuse, harass, harm, stalk, threaten or otherwise violate the legal rights (including without limitation rights of privacy and publicity) of others;
                            Publish, post, upload, distribute or disseminate any profane, defamatory, infringing, hateful, distasteful, obscene or unlawful topic, name, information, materials or content;
                            Use the Service or engage with other Users for any purpose that is in violation of local, state, national, or international law, rule or regulation, including without limitation wage and hour and working condition laws and regulations;
                            Upload files that contain software or other material that violates the rights of any third party, including without limitation intellectual property rights or rights of privacy or publicity;
                            Upload files that contain viruses, Trojan horses, worms, time bombs, spiders, cancel bots, corrupted files, or any other similar software, malware or materials that may damage, interfere with, disrupt, impair, disable or otherwise overburden the operation of any device, computer system or network;
                            Take any action that would undermine any aspect of the Service or use the Service in any manner that could interfere with, disrupt, or inhibit other users from fully enjoying the Service or that could damage, disable, overburden or impair the functioning of the Service in any manner;
                            Attempt to gain unauthorized access to the Service, other User accounts, or other device, computer system or networks connected to the Service;
                            Harvest or otherwise collect information about Users without their consent;
                            Advertise or offer to sell any goods or services for any commercial purpose (except as expressly set forth herein) on the Service that are not appropriate or relevant to the Service;
                            Conduct or forward pyramid schemes, chain letters, surveys or contests on or through the Service, except where sponsored or created by Sittercity;
                            Impersonate another person or allow any other person or entity to use your user name, password or membership;
                            Post the same content repeatedly or spam - spamming is strictly prohibited;
                            Download any file posted by another User that you know, or reasonably should know, cannot be legally distributed through the Service;
                            Access, download, or copy any information, content and/or materials from the Service through artificial means (including without limitation spiders, scrapers, hacking devices, computer programs, bots or other such means);
                            Reproduce, duplicate, copy, sell, re-sell or exploit any information, materials or content on the Service; and/or
                            Restrict or inhibit any other User from using and enjoying the Service.
                            Sittercity reserves all of its rights under the Communications Decency Act, including without limitation its right to remove anything objectionable to Sittercity in its sole discretion. You may report any alleged improprieties by any User to Sittercity by email at support@sittercity.com. However, enforcement of these Terms of Use is solely at Sittercity's discretion, and failure to enforce in some instances does not constitute a waiver of Sittercity’s right to enforce in other instances. In addition, these Terms of Use do not create any private right of action on the part of any User or third party or any reasonable expectation that the Service will not contain any content or conduct that is prohibited by such Terms of Use.

                            9. Account Security. You are responsible for maintaining the confidentiality of passwords and account information for the Service, and you are fully responsible for all activities that occur under your account. You agree to immediately notify Sittercity of any unauthorized use of accounts or any other breach of security.

                            10. Third-Party Services and Content. The Service may contain links or otherwise contain or provide access to third-party products, services, websites, advertisers, applications, information, and content (collectively, “Third-Party Services and Content”), which access is provided solely for convenience. For example, the Service may provide access to a third-party payment processing service that enable caregivers to collect payments through the Service from parents who engage them and may make third-party content available through the Service, such as in the Facebook pages, Blog and Twitter account. You understand and agree that such Third-Party Services and Content are not provided by Sittercity, and Sittercity does not control or endorse and does not make any representations or warranties regarding such Third-Party Services and Content. YOU UNDERSTAND AND AGREE THAT USE OF SUCH THIRD-PARTY SERVICES AND CONTENT IS AT YOUR OWN RISK, THAT SITTERCITY TERMS OF USE AND POLICIES DO NOT APPLY TO SUCH THIRD-PARTY SERVICES AND CONTENT, AND THAT SITTERCITY IS NOT RESPONSIBLE FOR THE PRIVACY OR BUSINESS PRACTICES OR OTHER POLICIES OF SUCH THIRD-PARTY SERVICES AND CONTENT OR FOR THE ACCURACY, COMPLETENESS, SAFETY OR QUALITY OF THE THIRD-PARTY SERVICES AND CONTENT. YOU SHOULD CAREFULLY REVIEW ANY APPLICABLE TERMS AND POLICIES THAT APPLY TO ANY THIRD-PARTY SERVICES AND CONTENT. SITTERCITY IS NOT RESPONSIBLE OR LIABLE IN ANY MANNER FOR SUCH THIRD-PARTY SERVICES AND CONTENT, OR FOR ANY LOSS OR DAMAGE OF ANY SORT INCURRED AS THE RESULT THEREOF, AND SITTERCITY HEREBY EXPRESSLY DISCLAIMS, AND YOU HEREBY EXPRESSLY RELEASE SITTERCITY FROM, ANY AND ALL LIABILITY WHATSOEVER FOR ANY CONTROVERSIES, CLAIMS, SUITS, INJURIES, LIABILITIES AND/OR DAMAGES ARISING FROM AND/OR IN ANY WAY RELATED TO SUCH THIRD-PARTY SERVICES AND CONTENT, INCLUDING WITHOUT LIMITATION RELATING TO AVAILABILITY, TERMS OF USE, PRIVACY, INFORMATION, CONTENT, MATERIALS, ADVERTISING, CHARGES, PAYMENT, PRODUCTS AND/OR SERVICES.</Text>
                    </View>
        </ScrollView>
    )
}

export default Terms